(6-2)中級 従業員曖昧検索
Atsushi0624/ex-emp-management-bugfix pull request #14
Opened 2022-06-10 00:33 UTC by Atsushi0624

従業員一覧画面に従業員名で曖昧検索するための検索フォームを用意して曖昧索機能を追加しました。
確認よろしくお願いいたします。

2022-06-10 02:25 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-10 02:25 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	if(name == null) {
空文字はnullではなく""で入っていた気がします。
ご確認お願いします。

私の認識が間違っていたら修正不要です。

2022-06-10 02:25 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
>  }
今後のページング処理をシンプルにするために、Controllerにおいて一覧表示を行うshowListメソッドと、曖昧検索を行うメソッドを統合しましょう。

2022-06-10 07:58 UTC, Atsushi0624 commented
全件表示と検索機能のメソッドの統合しました。
また、伊賀さんがおっしゃるとおり空文字はnullではなく""でした。
今回は""を受け取り曖昧検索を行った場合でも全件検索扱いになるため、特に対応は行いませんでした。

2022-06-12 23:36 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。
プルリクやコミットの粒度がとてもわかりやすいです。

2022-06-12 23:36 UTC, merged