(5-3)上級 パスワード暗号化orハッシュ化
Atsushi0624/ex-emp-management-bugfix pull request #15
Opened 2022-06-10 01:41 UTC by Atsushi0624

管理者登録時、ログイン時にパスワードをハッシュ化させるように変更しました。
確認よろしくお願いいたします。

2022-06-10 02:44 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-10 02:44 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			administrator.setPassword(hashPassword);
おそらくこのやり方ですと、
・インサート時にハッシュ化される値
と
・ログイン時にハッシュ化される値
が同じものになってしまいそうです。

レインボーアタックという攻撃に対する脆弱性につながってしまいます。

お客さまからの要望にあった通り、以下で実装をお願いします。

　　アルゴリズムはbcryptを使って欲しい。
　　(SpringSecurityの機能を使って欲しい)

2022-06-10 07:26 UTC, Atsushi0624 commented
Spring Securityの機能を利用してハッシュ化機能を実装しました。
また、同時に5-4の機能も実装したので、すみませんがこちらも確認お願いします。

2022-06-12 23:39 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。
プルリクやコミットの粒度がとてもわかりやすいです。

2022-06-12 23:39 UTC, merged