(1-3)中級 Eメール重複チェック
Atsushi0624/ex-emp-management-bugfix pull request #7
Opened 2022-06-09 06:14 UTC by Atsushi0624

管理者登録処理前にメールアドレスの重複をチェックするように変更しました。
また、重複があった場合エラーメッセージを表示させるようにしました。
確認お願いします。

2022-06-09 06:41 UTC, igamasayuki requested changes
やっていることは問題ありませんが、
若干修正がしづらいコードになっているため、以下の方針に修正をお願いします。
コントローラの最初の方でチェックを終わらせるようなイメージです。

○今回の方針
　・AdministratorServiceにseachByMailAddress()を作る
　・AdministratorControllerで上記のメソッドを呼ぶ
　・もしnullならエラー、nullじゃなければ登録処理

なお、今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2022-06-09 07:25 UTC, Atsushi0624 commented
いただいたレビューを参考にコントローラで重複チェックを行うように修正しました。
確認よろしくお願いします。

2022-06-09 23:25 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 23:25 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +
　resultにエラーメッセージを登録できていて汎用性が高く良いと思います。

2022-06-09 23:25 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +
再度のお願いです。

現状のままですと、入力値エラーが全部解消した後に、メールアドレス重複チェックのエラーが出ることになるため、
全部のエラーメッセージが同時に出るように改修をお願いします。

意味がわからない場合はご相談ください。

2022-06-09 23:25 UTC, igamasayuki commented on src/main/resources/templates/administrator/insert.html
>  										<label th:if="${#fields.hasErrors('mailAddress')}" th:errors="*{mailAddress}" class="error-messages">
59行目が不要で、60行目で一緒にエラーメッセージが出るようになりませんか？

2022-06-10 00:41 UTC, Atsushi0624 commented
全部のエラーメッセージが同時に出るように修正しました。
度々申し訳ございませんが、確認よろしくお願いいたします。

2022-06-10 02:20 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2022-06-10 02:20 UTC, merged