(1-5)中級 確認用パスワード
Atsushi0624/ex-emp-management-bugfix pull request #8
Opened 2022-06-09 06:55 UTC by Atsushi0624

確認用パスワードの入力フォームを追加しました。
JavaScriptでキーが押される度にパスワードの確認を行い、パスワードが一致したときのみ、登録ボタンが押せるように修正しました。

2022-06-09 23:29 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 23:29 UTC, igamasayuki commented on src/main/resources/static/js/password_check.js
> +});
　jQueryを使用した場合でも、登録ボタンを押された際に
　サーバー側でもチェックを行うようにしてください。
　(jQueryを使用していても良いですが、必ずサーバー側でもチェックが必要です。
　理由：ブラウザでJavaScriptを無効にしていた場合でもチェックできるため)

2022-06-10 00:58 UTC, Atsushi0624 commented
サーバ側でもパスワードチェックを行うように修正しました。
確認よろしくお願いいたします。

2022-06-10 02:21 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2022-06-10 02:22 UTC, merged